// Mocks generated by Mockito 5.0.16 from annotations
// in app_template/test/app/pages/home/bloc/home_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:app_template/src/app/pages/home/home_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [HomeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeService extends _i1.Mock implements _i2.HomeService {
  MockHomeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> increment() =>
      (super.noSuchMethod(Invocation.method(#increment, []),
          returnValue: Future<int>.value(0)) as _i3.Future<int>);
  @override
  _i3.Future<int> decrement() =>
      (super.noSuchMethod(Invocation.method(#decrement, []),
          returnValue: Future<int>.value(0)) as _i3.Future<int>);
  @override
  _i3.Future<int> reset() => (super.noSuchMethod(Invocation.method(#reset, []),
      returnValue: Future<int>.value(0)) as _i3.Future<int>);
  @override
  _i3.Future<int> getCounter() =>
      (super.noSuchMethod(Invocation.method(#getCounter, []),
          returnValue: Future<int>.value(0)) as _i3.Future<int>);
  @override
  String toString() => super.toString();
}
